### ISSUE TITLE
Test fails due to Lollipop checks setNextMediaPlayer() method is more strictly

### ISSUE THREAD

**Issue by h6ah4i** [h6ah4i/android-openslmediaplayer#2]
The setNextMediaPlayer() has changed since Lollipop. It verifies the passed next player instance more strictly. Need to implement compatible behavior for older devices.

**Comment by sean-xiaoyin** [comment]
So this has been fixed?

**Comment by h6ah4i** [comment]
Currently, the develop branch includes this fix.
