### ISSUE TITLE
Problem playing mp3 with irregular frequency

### ISSUE THREAD

**Issue by blocke79** [h6ah4i/android-openslmediaplayer#20]
I'm having issues playing mp3's with irregular frequencies (eg 24000 instead of 44100 or 48000).

Is this a known issue? It works in the standard player but not with the OpenSL or Hybrid.

Thanks in advance.

**Comment by h6ah4i** [comment]
Hi. Could you send me the MP3 file which can reproduce the same issue? (Send me an email if the MP3 cannot be uploaded on public places. =>  h6a.h4i.0@gmail.com)

Also I need more details of your setup; 

- Version of OpenSLMediaPlayer library
- Android OS version
- Device model

Thanks.

**Comment by blocke79** [comment]
Hi. Thanks for the super fast reply!

- Using version 0.7.0 ( compile 'com.h6ah4i.android:openslmediaplayer:0.7.0')
- Android version 5.1.1
- Device is a Sony Xperia Z5 (E6653) but all other devices we have tested with have the same issue (Note 3, Galaxy S5).

Here are link to a couple of sample files (Github doesn't allow mp3's)

https://www.dropbox.com/s/zbvj84tt6o6zfq4/Aaj%20Din%20Chadheya-%28Mr-Jatt.com%29.mp3?dl=0
https://www.dropbox.com/s/tu7ctl8yx3eqtbh/Chand%20Chupa%20Badal%20Mein-%28Mr-Jatt.com%29.mp3?dl=0

Thanks.

**Comment by h6ah4i** [comment]
Thanks, I found out the cause. The uploaded MP3s have 22kHz sample rate but this library does not handle them properly. I will try to fix the issue on this weekend.

**Comment by blocke79** [comment]
Thank you. Very much appreciated!.

**Comment by h6ah4i** [comment]
@blocke79 Hi. I have just released v0.7.1 and it includes the fix of this issue. Could you try it?

**Comment by blocke79** [comment]
Its working great. Thanks for the quick fix!

**Comment by h6ah4i** [comment]
😄
