### ISSUE TITLE
Minimum example with visualizer?

### ISSUE THREAD

**Issue by liuzhen2008** [h6ah4i/android-openslmediaplayer#25]
The current minimal example does exactly what a media player does which isn't exactly useful.

How do we show the visualizers?

It takes some time to setup the environment and build these whole project.

**Comment by h6ah4i** [comment]
Hi. Sorry, I do not have any minimal example code that shows how to use Visualizer.

However, this library provides almost the same interface with official Visualizer class, so you can refer to the [Visualizer](https://developer.android.com/reference/android/media/audiofx/Visualizer.html) class document and official (old) [AudioFxDemo](https://android.googlesource.com/platform/development/+/master/samples/ApiDemos/src/com/example/android/apis/media/AudioFxDemo.java) code.

Also, I found a guy creating minimal visualizer app. Its most of code is just copied from AudioFxDemo.
- http://android-er.blogspot.jp/2015/02/create-audio-visualizer-for-mediaplayer.html


---

FYI: Here is a tiny code snippet how to migrate official `Visualizer` to `StandardVisualizer` of this library.

#### Visualizer 

```java
MediaPlayer player;
Visualizer visualizer:

player = new MediaPlayer();
player.setDataSource("...");
player.prepare();

visualizer = new Visualizer(player.getAudioSessionId());
visualizer.setCaptureSize(Visualizer.getCaptureSizeRange()[1]);
visualizer.setDataCaptureListener(
    new Visualizer.OnDataCaptureListener() {
        @Overrides
        public void onWaveFormDataCapture(Visualizer visualizer, byte[] bytes, int samplingRate) {
        }

        @Overrides
        public void onFftDataCapture(Visualizer visualizer, byte[] bytes, int samplingRate) {
        }
    },
    Visualizer.getMaxCaptureRate(), 
    true, // capture fft
    true // capture waveform
    );

visualizer.setEnabled(true);

player.start();

...

player.pause();

visualizer.setEnabled(false);

visualizer.release();
player.release();
```

#### StandardVisualizer 

```java
Context context = ...;
IMediaPlayerFactory factory;
IBasicMediaPlayer player;
IVisualizer visualizer;

factory = new StandardMediaPlayerFactory(context);

player = new factory.createMediaPlayer();
player.setDataSource("...");
player.prepare();

visualizer = factory.createVisualizer(player);
visualizer.setCaptureSize(StandardVisualizer.sGetCaptureSizeRange()[1]);
visualizer.setDataCaptureListener(
    new IVisualizer.OnDataCaptureListener() {
        @Overrides
        public void onWaveFormDataCapture(IVisualizer visualizer, byte[] bytes, int samplingRate) {
        }

        @Overrides
        public void onFftDataCapture(IVisualizer visualizer, byte[] bytes, int samplingRate) {
        }
    },
    StandardVisualizer.sGetMaxCaptureRate(), 
    true, // capture fft
    true // capture waveform
    );

visualizer.setEnabled(true);
player.start();

...

player.pause();
visualizer.setEnabled(false);

visualizer.release();
player.release();
factory.release();
```

**Comment by liuzhen2008** [comment]
THanks

**Comment by billyjoker** [comment]
Hi, i know that it is a closed issue, but i'm working hard to figure out why with no volume level it is still having an amplitude level in the graph, i mean, independent of the volume level, if the file contains amplitude signal, it has to be represented (wrongly because you can not hear anything). Hoe could i fix this bug ?? I've followed the demo code to reproduce this behaviour.
Thanks in advance!!
