### ISSUE TITLE
Lib size is too big

### ISSUE THREAD

**Issue by tuhin10** [h6ah4i/android-openslmediaplayer#33]
I am using compile 'com.h6ah4i.android:openslmediaplayer:0.7.3' but its adding ~10mb in my app apk. How can I use the java api?

**Comment by h6ah4i** [comment]
Ah, maybe the compiled binary contains debug info. I'll take a look at it! Thanks for reporting.

**Comment by h6ah4i** [comment]
Fixed. The library size is about 2.5 MiB (includes `arm64-v8a`, `armeabi`, `armeabi-v7a`, `x86`, `x86_64` native binaries) in 0.7.4.

**Comment by tuhin10** [comment]
Something's wrong in the latest version, its sniping fastforwding on its own.
