### ISSUE TITLE
Question: can someone explain me the differences from every type of player please?

### ISSUE THREAD

**Issue by SluggedGerm2** [h6ah4i/android-openslmediaplayer#38]
I don't find the real differences from OpenSLPlayer, StandardMediaPlayer and IBasicMediaPlayer.
Which one should I use?

**Comment by h6ah4i** [comment]
Hi. Here's the summary of each classes/interface.

| class | description |
|---|---|
| `IBasicMediaPlayer` | A common interface of `OpenSLMediaPlayer` and `StandardMediaPlayer` |
| `StandardMediaPlayer` | A media player that uses [Android's MediaPlayer](https://developer.android.com/reference/android/media/MediaPlayer.html) backend  |
| `OpenSLMediaPlayer` | A media player that uses C++ OpenSL ES APIs for its backend |

ref.) https://github.com/h6ah4i/android-openslmediaplayer/wiki/API-Overview

**Comment by SluggedGerm2** [comment]
Tanks,
So which one do you suggest?
