### ISSUE TITLE
Nullpointer exception

### ISSUE THREAD

**Issue by Ph1b** [h6ah4i/android-openslmediaplayer#5]
While playing around a bit with the playstore version this crash occured: Cant reproduce.

<pre><code>E/AndroidRuntime(19961): Process: com.h6ah4i.android.example.openslmediaplayer, PID: 19961
E/AndroidRuntime(19961): java.lang.NullPointerException
E/AndroidRuntime(19961): 	at com.h6ah4i.android.example.openslmediaplayer.app.utils.NotificationBuilder.createServiceNotification(NotificationBuilder.java:48)
E/AndroidRuntime(19961): 	at com.h6ah4i.android.example.openslmediaplayer.app.model.GlobalAppController.checkAndUpdateForegroundState(GlobalAppController.java:1934)
E/AndroidRuntime(19961): 	at com.h6ah4i.android.example.openslmediaplayer.app.model.GlobalAppController.onPlayerStateChanged(GlobalAppController.java:1369)
E/AndroidRuntime(19961): 	at com.h6ah4i.android.example.openslmediaplayer.app.model.GlobalAppController.setPlayerState(GlobalAppController.java:1364)
E/AndroidRuntime(19961): 	at com.h6ah4i.android.example.openslmediaplayer.app.model.GlobalAppController.playerRelease(GlobalAppController.java:841)
E/AndroidRuntime(19961): 	at com.h6ah4i.android.example.openslmediaplayer.app.model.GlobalAppController.releaseAllPlayerResources(GlobalAppController.java:1693)
E/AndroidRuntime(19961): 	at com.h6ah4i.android.example.openslmediaplayer.app.model.GlobalAppController.onReceivePlayerControlEvent(GlobalAppController.java:601)
E/AndroidRuntime(19961): 	at com.h6ah4i.android.example.openslmediaplayer.app.model.GlobalAppController.onReceiveAppEvent(GlobalAppController.java:517)
E/AndroidRuntime(19961): 	at com.h6ah4i.android.example.openslmediaplayer.app.model.GlobalAppController$AppEventReceiver.onReceiveAppEvent(GlobalAppController.java:128)
E/AndroidRuntime(19961): 	at com.h6ah4i.android.example.openslmediaplayer.app.model.GlobalAppController$AppEventReceiver.onReceiveAppEvent(GlobalAppController.java:106)
E/AndroidRuntime(19961): 	at com.h6ah4i.android.example.openslmediaplayer.app.framework.AppEventBus$Receiver.onReceive(AppEventBus.java:50)
E/AndroidRuntime(19961): 	at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
E/AndroidRuntime(19961): 	at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
E/AndroidRuntime(19961): 	at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
E/AndroidRuntime(19961): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(19961): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(19961): 	at android.app.ActivityThread.main(ActivityThread.java:5146)
E/AndroidRuntime(19961): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(19961): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(19961): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
E/AndroidRuntime(19961): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
E/AndroidRuntime(19961): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager( 2021):   Force finishing activity com.h6ah4i.android.example.openslmediaplayer/.app.MainActivity
W/ActivityManager( 2021): Activity pause timeout for ActivityRecord{422dd178 u0 com.h6ah4i.android.example.openslmediaplayer/.app.MainActivity t433 f}</pre></code>

**Comment by h6ah4i** [comment]
Thanks for the report. I'll take a look.
